Added Acuracia, Especificidade, Seletividade to dicionario.md
PizzaDeDados/datascience-pizza pull request #373
Opened 2019-10-19 19:16 UTC by machadowisck

2020-08-25 19:48 UTC, leportella requested changes
Pode por favor adicionar referência bibliografica?

2020-10-07 22:41 UTC, jtemporal requested changes

2020-10-07 22:41 UTC, jtemporal commented on dicionario.md
> +
```suggestion
```

2020-10-07 22:41 UTC, jtemporal commented on dicionario.md
> +
```suggestion
```

2020-10-07 22:41 UTC, jtemporal commented on dicionario.md
> +A especificidade está para a condição negativa assim como a revocação está para a condição positiva.
```suggestion
A especificidade, também é chamada de seletivedade, está para a condição negativa assim como a revocação está para a condição positiva.
```

2020-10-07 22:41 UTC, jtemporal commented on dicionario.md
> +Ver [Especificidade](https://github.com/leportella/datascience-pizza/blob/master/dicionario.md#especificidade).
```suggestion
Ver [Especificidade](https://github.com/PIzzaDeDados/datascience-pizza/blob/master/dicionario.md#especificidade).
```

2020-10-08 21:42 UTC, jtemporal commented
Olá tudo bom? Estou fechando esse pull request pois já faz algum tempo que ele foi aberto e não recebemos as correções pedidas. Por favor, sinta-se à vontade para re-submeter o pull request com as atualizações necessárias. Obrigada pela contribuição =)

2020-10-08 21:42 UTC, closed without merging